version: '3'
services:
  webappbot:
    environment: 
      - TOKEN=${AGRIWEATHBOT_TOKEN}
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - .:/webapp
    command: python3 -u webappbot.py